#!/bin/sh
# SPDX-FileCopyrightText: © 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

if command -v apt-get >/dev/null; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y --no-install-recommends "$@"
    apt-get clean
    rm -rf /var/lib/apt/lists/*
elif command -v dnf >/dev/null; then
    dnf install -y --setopt=install_weak_deps=False "$@"
    dnf clean all
elif command -v yum >/dev/null; then
    yum install -y "$@"
    yum clean all
elif command -v apk >/dev/null; then
    apk add --no-cache "$@"
elif command -v zypper >/dev/null; then
    zypper install -y --no-recommends "$@"
    zypper clean -a
fi
