name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            image-name: python-base-ubuntu
            from: ubuntu:26.04@sha256:5e275723f82c67e387ba9e3c24baa0abdcb268917f276a0561c97bef9450d0b4
          - name: ubuntu-cloud-archive
            image-name: python-base-ubuntu-cloud-archive
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:2026.1@sha256:2e655a7437a95ebb4065b5328e916195e39a79449c8593af015acfc67b2fdfb9
          - name: ubuntu-cloud-archive-legacy
            image-name: python-base
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:2026.1@sha256:2e655a7437a95ebb4065b5328e916195e39a79449c8593af015acfc67b2fdfb9
          - name: debian
            image-name: python-base-debian
            from: debian:trixie@sha256:35b8ff74ead4880f22090b617372daff0ccae742eb5674455d542bef71ef1999
          - name: rockylinux
            image-name: python-base-rockylinux
            from: rockylinux/rockylinux:10@sha256:f4da504c18e7aced902f4f728cde787cd9d9b817bc639fe171026d18364dca6c
          - name: almalinux
            image-name: python-base-almalinux
            from: almalinux:10@sha256:4e61a558860472c243bd05cb47da1e0c85006f08877ab419d5de7dbb59ce842e
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          image-name: ${{ matrix.image-name }}
          build-args: FROM=${{ matrix.from }}
          push: ${{ github.event_name != 'pull_request' }}
