name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

permissions:
  contents: read

jobs:
  image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            image-name: python-base-ubuntu
            from: ubuntu:24.04@sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b
          - name: ubuntu-cloud-archive
            image-name: python-base-ubuntu-cloud-archive
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:main@sha256:16b2a21d51f516b4c668a8d8c03c42fd2bad8668320a0a84d683900551d60e32
          - name: ubuntu-cloud-archive-legacy
            image-name: python-base
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:main@sha256:16b2a21d51f516b4c668a8d8c03c42fd2bad8668320a0a84d683900551d60e32
          - name: debian
            image-name: python-base-debian
            from: debian:trixie@sha256:e2d08da6f42ef4b09b165d55528a12727aeed8240dc9edf888e3ec07e10ef9da
          - name: rockylinux
            image-name: python-base-rockylinux
            from: rockylinux/rockylinux:10@sha256:f4da504c18e7aced902f4f728cde787cd9d9b817bc639fe171026d18364dca6c
          - name: almalinux
            image-name: python-base-almalinux
            from: almalinux:10@sha256:48ae80a8d5baaa6592cdd55dd1bec127c6bea76093a89b2c45dd613f0720687c
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@a1ad25c00b6bbf44621748b3a9ed664c6b6cf929 # main
        with:
          image-name: ${{ matrix.image-name }}
          build-args: FROM=${{ matrix.from }}
          push: ${{ github.event_name != 'pull_request' }}
