name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write
  packages: write
  security-events: write

jobs:
  image:
    uses: vexxhost/github-actions/.github/workflows/image.yml@main
    strategy:
      matrix:
        release:
          - zed
          - antelope
          - bobcat
          - caracal
    with:
      context: ${{ matrix.release }}
      image-ref: ghcr.io/${{ github.repository_owner }}/python-base
      tags: |
        type=sha,suffix=-${{ matrix.release }}
        type=raw,value=${{ matrix.release }}
        type=raw,value=${{ matrix.release }}-{{date 'X'}}
      push: ${{ github.ref == 'refs/heads/main' }}
